"""empty message

Revision ID: 025cbcf07809
Revises: e98266c75b2d
Create Date: 2020-06-01 12:15:20.397906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025cbcf07809'
down_revision = 'e98266c75b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
