"""empty message

Revision ID: 171c3e03a3f7
Revises: 4061bce57d40
Create Date: 2020-06-09 13:11:12.705584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171c3e03a3f7'
down_revision = '4061bce57d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'time')
    # ### end Alembic commands ###
