"""empty message

Revision ID: 19e8a81a4551
Revises: 3c06502b680c
Create Date: 2020-06-16 10:53:46.419810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e8a81a4551'
down_revision = '3c06502b680c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('appointments_userId_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    op.drop_column('appointments', 'userId')
    op.add_column('interpreters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('interpreters_userId_fkey', 'interpreters', type_='foreignkey')
    op.create_foreign_key(None, 'interpreters', 'users', ['user_id'], ['id'])
    op.drop_column('interpreters', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interpreters', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interpreters', type_='foreignkey')
    op.create_foreign_key('interpreters_userId_fkey', 'interpreters', 'users', ['userId'], ['id'])
    op.drop_column('interpreters', 'user_id')
    op.add_column('appointments', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_userId_fkey', 'appointments', 'users', ['userId'], ['id'])
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
