"""empty message

Revision ID: 3d53f4960182
Revises: 5897c9598c93
Create Date: 2020-06-24 12:13:37.013471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d53f4960182'
down_revision = '5897c9598c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_password', sa.String(length=256), nullable=True))
    op.drop_column('appointments', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'meeting_password')
    # ### end Alembic commands ###
