"""empty message

Revision ID: 49920d8a8e35
Revises: dbf514de5130
Create Date: 2020-06-08 13:28:47.491914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49920d8a8e35'
down_revision = 'dbf514de5130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=100), nullable=True),
    sa.Column('target_languages', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
