"""empty message

Revision ID: 7cd1c16d6d03
Revises: 5581ad4d2465
Create Date: 2020-09-10 10:23:52.158080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd1c16d6d03'
down_revision = '5581ad4d2465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_language', sa.String(length=100), nullable=True),
    sa.Column('target_languages', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('category_type', sa.Text(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('join_url', sa.String(length=256), nullable=True),
    sa.Column('start_url', sa.String(length=550), nullable=True),
    sa.Column('meeting_id', sa.String(length=15), nullable=True),
    sa.Column('meeting_password', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interpreters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=150), nullable=True),
    sa.Column('native_language', sa.String(length=150), nullable=True),
    sa.Column('target_languages', sa.Text(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=150), nullable=True),
    sa.Column('field_of_expertise', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('interpreting_service', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('appoinment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appoinment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned')
    op.drop_table('interpreters')
    op.drop_table('appointments')
    # ### end Alembic commands ###
