"""empty message

Revision ID: 9ec4ae830de9
Revises: dec5da894130
Create Date: 2020-06-22 11:26:52.739569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec4ae830de9'
down_revision = 'dec5da894130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('appointments', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('appointments', 'url')
    op.drop_column('appointments', 'password')
    op.drop_column('appointments', 'meeting_id')
    # ### end Alembic commands ###
