"""empty message

Revision ID: dbf514de5130
Revises: a8aca13630f4
Create Date: 2020-06-08 13:19:17.878197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf514de5130'
down_revision = 'a8aca13630f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('time', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'time')
    # ### end Alembic commands ###
