"""empty message

Revision ID: dccdb90fc928
Revises: 147d0e053e14
Create Date: 2020-08-04 11:01:35.050982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccdb90fc928'
down_revision = '147d0e053e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_type', sa.String(length=20), nullable=True))
    op.drop_column('appointments', 'type_appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('type_appointment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'meeting_type')
    # ### end Alembic commands ###
